mod 'boxen', '3.9.1', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib', '4.5.1', :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod 'homebrew', '1.9.8', :github_tarball => 'boxen/puppet-homebrew'
#mod 'module-data', '0.0.4',  :github_tarball => 'ripienaar/puppet-module-data'
