mod 'boxen', '3.3.0', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib', '4.0.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod 'homebrew', '1.1.2', :github_tarball => 'boxen/puppet-homebrew'
mod 'module-data', '0.0.1',  :github_tarball => 'ripienaar/puppet-module-data'
